global:
  scrape_interval: 15s  # Intervalo para coletar as métricas

scrape_configs:
  - job_name: 'python_app'  # Nome do trabalho para monitorar seu aplicativo Python
    static_configs:
      - targets: ['host.docker.internal:8000']  # Endereço da sua aplicação em execução
